### ISSUE TITLE
Panic with invalid config

### ISSUE THREAD

**Issue by jsimonetti** [hashicorp/hcl#110]
During some trial and error I accidentally hit the following panic:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x8 pc=0x4c6a2a]

goroutine 1 [running]:
panic(0x559420, 0xc82000a0e0)
        /usr/lib/go/src/runtime/panic.go:464 +0x3e6
github.com/hashicorp/hcl/hcl/ast.(*ObjectList).Filter(0xc82000ea40, 0xc8200a18b0, 0x1, 0x1, 0x2)
        /home/jeroen/dev/src/github.com/hashicorp/hcl/hcl/ast/ast.go:59 +0xaa
github.com/hashicorp/hcl.(*decoder).decodeStruct(0xc8200a3dd8, 0xc82000ea20, 0x15, 0x7f5cba96a1c0, 0xc82000ea40, 0x5565a0, 0xc82000b370, 0x199, 0x0, 0x0)
        /home/jeroen/dev/src/github.com/hashicorp/hcl/decoder.go:603 +0x1d76
github.com/hashicorp/hcl.(*decoder).decode(0xc8200a3dd8, 0xc82000ea20, 0x15, 0x7f5cba96a1f0, 0xc8200769b0, 0x5565a0, 0xc82000b370, 0x199, 0x0, 0x0)
        /home/jeroen/dev/src/github.com/hashicorp/hcl/decoder.go:108 +0x9a4
github.com/hashicorp/hcl.(*decoder).decodePtr(0xc8200a3dd8, 0xc82000ea20, 0x15, 0x7f5cba96a1f0, 0xc8200769b0, 0x5158a0, 0xc820028140, 0x196, 0x0, 0x0)
        /home/jeroen/dev/src/github.com/hashicorp/hcl/decoder.go:397 +0x151
github.com/hashicorp/hcl.(*decoder).decode(0xc8200a3dd8, 0xc82000ea20, 0x15, 0x7f5cba96a1f0, 0xc8200769b0, 0x5158a0, 0xc820028140, 0x196, 0x0, 0x0)
        /home/jeroen/dev/src/github.com/hashicorp/hcl/decoder.go:102 +0x862
github.com/hashicorp/hcl.(*decoder).decodeStruct(0xc8200a3dd8, 0xc82000b310, 0xd, 0x7f5cba96a1c0, 0xc82000e980, 0x556720, 0xc820028140, 0x199, 0x0, 0x0)
        /home/jeroen/dev/src/github.com/hashicorp/hcl/decoder.go:627 +0x22d0
github.com/hashicorp/hcl.(*decoder).decode(0xc8200a3dd8, 0xc82000b310, 0xd, 0x7f5cba96a320, 0xc82006a900, 0x556720, 0xc820028140, 0x199, 0x0, 0x0)
        /home/jeroen/dev/src/github.com/hashicorp/hcl/decoder.go:108 +0x9a4
github.com/hashicorp/hcl.(*decoder).decodeSlice(0xc8200a3dd8, 0xc82000b2c0, 0xa, 0x7f5cba96a1c0, 0xc82000e920, 0x51b780, 0xc82000e960, 0x97, 0x0, 0x0)
        /home/jeroen/dev/src/github.com/hashicorp/hcl/decoder.go:446 +0x5af
github.com/hashicorp/hcl.(*decoder).decode(0xc8200a3dd8, 0xc82000b2c0, 0xa, 0x7f5cba96a1c0, 0xc82000e920, 0x51b780, 0xc820076a38, 0x197, 0x0, 0x0)
        /home/jeroen/dev/src/github.com/hashicorp/hcl/decoder.go:104 +0x8cc
github.com/hashicorp/hcl.(*decoder).decodeStruct(0xc8200a3dd8, 0x589128, 0x4, 0x7f5cba96a1c0, 0xc82000e360, 0x568e20, 0xc820076a00, 0x199, 0x0, 0x0)
        /home/jeroen/dev/src/github.com/hashicorp/hcl/decoder.go:627 +0x22d0
github.com/hashicorp/hcl.(*decoder).decode(0xc8200a3dd8, 0x589128, 0x4, 0x7f5cba96a1c0, 0xc82000e360, 0x568e20, 0xc820076a00, 0x199, 0x0, 0x0)
        /home/jeroen/dev/src/github.com/hashicorp/hcl/decoder.go:108 +0x9a4
github.com/hashicorp/hcl.(*decoder).decodePtr(0xc8200a3dd8, 0x589128, 0x4, 0x7f5cba96a1c0, 0xc82000e360, 0x5159c0, 0xc820028038, 0x196, 0x0, 0x0)
        /home/jeroen/dev/src/github.com/hashicorp/hcl/decoder.go:397 +0x151
github.com/hashicorp/hcl.(*decoder).decode(0xc8200a3dd8, 0x589128, 0x4, 0x7f5cba96a1c0, 0xc82000e360, 0x5159c0, 0xc820028038, 0x196, 0x0, 0x0)
        /home/jeroen/dev/src/github.com/hashicorp/hcl/decoder.go:102 +0x862
github.com/hashicorp/hcl.DecodeObject(0x512ba0, 0xc820028038, 0x7f5cba96a1c0, 0xc82000e360, 0x0, 0x0)
        /home/jeroen/dev/src/github.com/hashicorp/hcl/decoder.go:60 +0x25f
github.com/hashicorp/hcl.Unmarshal(0xc820090300, 0xf8, 0x100, 0x512ba0, 0xc820028038, 0x0, 0x0)
        /home/jeroen/dev/src/github.com/hashicorp/hcl/decoder.go:32 +0xc6
main.main()
        /home/jeroen/dev/src/local/config/config.go:33 +0x117
exit status 2
```

Go file to reproduce:

```
package main

import (
        "fmt"

        "github.com/davecgh/go-spew/spew"
        "github.com/hashicorp/hcl"
)

func main() {
        var blob = `
name = "terraform-test-app"
listen = "tcp4://0.0.0.0:6386"
loglevel= "debug"

backend "test" {
    type "ldif" {
        path = "./test/"
    }
}

backend "test2" {
    type "ldif" {
        path = "./test2/"
    }
}

route {
    backend = "${backend.test2}"
}
`
        conf := &mainconf{}
        err := hcl.Unmarshal([]byte(blob), &conf)
        if err != nil {
                fmt.Printf("error %s", err)
        }

        spew.Dump(conf)
}

type mainconf struct {
        Name     string                   `hcl:"name"`
        Listen   string                   `hcl:"listen"`
        Loglevel string                   `hcl:"loglevel"`
        Backends map[string]BackendConfig `hcl:"backend"`
        Route    []Route                  `hcl:"route"`
}


type BackendConfig struct {
        Type map[string]Backend `hcl:"type"`
}

type Backend struct {
        Path string `hcl:"path"`
}

type Route struct {
        Backend *Backend `hcl:"backend"`
}
```

**Comment by mitchellh** [comment]
This now gives you a nice error message instead of a panic.
