### ISSUE TITLE
Input Causes Panic: "\0

### ISSUE THREAD

**Issue by BrianHicks** [hashicorp/hcl#127]
I've found a crashing input in HCL as of d7400db7143f8e869812e50a53acd6c8d92af3b8. Here's an [SSCCE](http://www.sscce.org/) demonstrating the problem.

```go
package main

import (
	"github.com/hashicorp/hcl"
)

var (
	data = "\"\\0"
)

func main() {
	var out interface{}
	hcl.Unmarshal([]byte(data), &out)
}
```

When run, this gives the following output:

```
panic: bytes.Buffer: UnreadRune: previous operation was not ReadRune

goroutine 1 [running]:
panic(0x1c8620, 0xc82000a8a0)
	/var/folders/f6/l26tk3xs5pjczcd5k5pcrmk00000gn/T/go-fuzz-build846495901/src/runtime/panic.go:481 +0x3e6
github.com/hashicorp/hcl/hcl/scanner.(*Scanner).unread(0xc82005f1e0)
	/var/folders/f6/l26tk3xs5pjczcd5k5pcrmk00000gn/T/go-fuzz-build846495901/src/github.com/hashicorp/hcl/hcl/scanner/scanner.go:106 +0xcd
github.com/hashicorp/hcl/hcl/scanner.(*Scanner).scanDigits(0xc82005f1e0, 0x0, 0x8, 0x2, 0x0)
	/var/folders/f6/l26tk3xs5pjczcd5k5pcrmk00000gn/T/go-fuzz-build846495901/src/github.com/hashicorp/hcl/hcl/scanner/scanner.go:537 +0x1ad
github.com/hashicorp/hcl/hcl/scanner.(*Scanner).scanEscape(0xc82005f1e0, 0x2200000000)
	/var/folders/f6/l26tk3xs5pjczcd5k5pcrmk00000gn/T/go-fuzz-build846495901/src/github.com/hashicorp/hcl/hcl/scanner/scanner.go:509 +0x143
github.com/hashicorp/hcl/hcl/scanner.(*Scanner).scanString(0xc82005f1e0)
	/var/folders/f6/l26tk3xs5pjczcd5k5pcrmk00000gn/T/go-fuzz-build846495901/src/github.com/hashicorp/hcl/hcl/scanner/scanner.go:493 +0x3d5
github.com/hashicorp/hcl/hcl/scanner.(*Scanner).Scan(0xc82005f1e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/var/folders/f6/l26tk3xs5pjczcd5k5pcrmk00000gn/T/go-fuzz-build846495901/src/github.com/hashicorp/hcl/hcl/scanner/scanner.go:166 +0x6bc
github.com/hashicorp/hcl/hcl/parser.(*Parser).scan(0xc82003bc88, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/var/folders/f6/l26tk3xs5pjczcd5k5pcrmk00000gn/T/go-fuzz-build846495901/src/github.com/hashicorp/hcl/hcl/parser/parser.go:376 +0x156
github.com/hashicorp/hcl/hcl/parser.(*Parser).objectKey(0xc82003bc88, 0x0, 0x0, 0x0, 0x0, 0x0)
	/var/folders/f6/l26tk3xs5pjczcd5k5pcrmk00000gn/T/go-fuzz-build846495901/src/github.com/hashicorp/hcl/hcl/parser/parser.go:196 +0x122
github.com/hashicorp/hcl/hcl/parser.(*Parser).objectItem(0xc82003bc88, 0x0, 0x0, 0x0)
	/var/folders/f6/l26tk3xs5pjczcd5k5pcrmk00000gn/T/go-fuzz-build846495901/src/github.com/hashicorp/hcl/hcl/parser/parser.go:125 +0xd5
github.com/hashicorp/hcl/hcl/parser.(*Parser).objectList(0xc82003bc88, 0x0, 0x0, 0x0)
	/var/folders/f6/l26tk3xs5pjczcd5k5pcrmk00000gn/T/go-fuzz-build846495901/src/github.com/hashicorp/hcl/hcl/parser/parser.go:70 +0x127
github.com/hashicorp/hcl/hcl/parser.(*Parser).Parse(0xc82003bc88, 0xc82005f1e0, 0x0, 0x0)
	/var/folders/f6/l26tk3xs5pjczcd5k5pcrmk00000gn/T/go-fuzz-build846495901/src/github.com/hashicorp/hcl/hcl/parser/parser.go:53 +0x166
github.com/hashicorp/hcl/hcl/parser.Parse(0x3d3000, 0x3, 0x200000, 0x1, 0x0, 0x0)
	/var/folders/f6/l26tk3xs5pjczcd5k5pcrmk00000gn/T/go-fuzz-build846495901/src/github.com/hashicorp/hcl/hcl/parser/parser.go:40 +0x24d
github.com/hashicorp/hcl.parse(0x3d3000, 0x3, 0x200000, 0x0, 0x0, 0x0)
	/var/folders/f6/l26tk3xs5pjczcd5k5pcrmk00000gn/T/go-fuzz-build846495901/src/github.com/hashicorp/hcl/parse.go:26 +0xc3
github.com/hashicorp/hcl.Unmarshal(0x3d3000, 0x3, 0x200000, 0x18d2e0, 0xc82000a820, 0x0, 0x0)
	/var/folders/f6/l26tk3xs5pjczcd5k5pcrmk00000gn/T/go-fuzz-build846495901/src/github.com/hashicorp/hcl/decoder.go:27 +0x7e
github.com/BrianHicks/fuzz-hcl.ParseSafely(0x3d3000, 0x3, 0x200000, 0x0, 0x0, 0x0, 0x0)
	/var/folders/f6/l26tk3xs5pjczcd5k5pcrmk00000gn/T/go-fuzz-build846495901/src/github.com/BrianHicks/fuzz-hcl/fuzz.go:20 +0xc1
github.com/BrianHicks/fuzz-hcl.Fuzz(0x3d3000, 0x3, 0x200000, 0x3)
	/var/folders/f6/l26tk3xs5pjczcd5k5pcrmk00000gn/T/go-fuzz-build846495901/src/github.com/BrianHicks/fuzz-hcl/fuzz.go:11 +0x105
go-fuzz-dep.Main(0x23a3e8)
	/var/folders/f6/l26tk3xs5pjczcd5k5pcrmk00000gn/T/go-fuzz-build846495901/src/go-fuzz-dep/main.go:49 +0x14c
main.main()
	/var/folders/f6/l26tk3xs5pjczcd5k5pcrmk00000gn/T/go-fuzz-build846495901/src/go.fuzz.main/main.go:10 +0x23
exit status 2
```

(and here it is when run through panicparse, for convenience)

```
panic: bytes.Buffer: UnreadRune: previous operation was not ReadRune

exit status 2
To see all goroutines, visit https://github.com/maruel/panicparse#GOTRACEBACK

1: running
                panic.go:481   panic(0x1c8620, 0xc82000a8a0)
    scanner     scanner.go:106 (*Scanner).unread(#2)
    scanner     scanner.go:537 (*Scanner).scanDigits(#2, 0, 0x8, 0x2, 0)
    scanner     scanner.go:509 (*Scanner).scanEscape(#2, 0x2200000000)
    scanner     scanner.go:493 (*Scanner).scanString(#2)
    scanner     scanner.go:166 (*Scanner).Scan(#2, 0, 0, 0, 0, 0, 0, 0, 0, 0)
    parser      parser.go:376  (*Parser).scan(#1, 0, 0, 0, 0, 0, 0, 0, 0, 0)
    parser      parser.go:196  (*Parser).objectKey(#1, 0, 0, 0, 0, 0)
    parser      parser.go:125  (*Parser).objectItem(#1, 0, 0, 0)
    parser      parser.go:70   (*Parser).objectList(#1, 0, 0, 0)
    parser      parser.go:53   (*Parser).Parse(#1, #2, 0, 0)
    parser      parser.go:40   Parse(0x3d3000, 0x3, 0x200000, 0x1, 0, 0)
    hcl         parse.go:26    parse(0x3d3000, 0x3, 0x200000, 0, 0, 0)
    hcl         decoder.go:27  Unmarshal(0x3d3000, 0x3, 0x200000, 0x18d2e0, 0xc82000a820, 0, 0)
    fuzz-hcl    fuzz.go:20     ParseSafely(0x3d3000, 0x3, 0x200000, 0, 0, 0, 0)
    fuzz-hcl    fuzz.go:11     Fuzz(0x3d3000, 0x3, 0x200000, 0x3)
    go-fuzz-dep main.go:49     Main(0x23a3e8)
    main        main.go:10     main()
```

**Comment by BrianHicks** [comment]
Other inputs that cause the same panic message:

```
	"v{\"\\0"
	"{:{:{:\"\\0"
	"\"\\0"
	"{:{:{:0\"\\0"
	"{:[{\"\\0"
	"v{v=0\"\\0"
	"v{v={\"\\0"
	"{\"\\0"
	"v={\"\\0"
	"{:{:{\"\\0"
	"v={v{\"\\0"
	"v={v=0\"\\0"
	"{:\"\\0"
	"v=0\"\\0"
	":{{\"\\0"
	"v=[\"\\0"
	"v{v=\"\\0"
	"/\x00\"\\0"
	"{:[\"\\0"
	":{{{\"\\0"
	"v{{{{{\"\\0"
	"v={v={\"\\0"
	"{:{:0\"\\0"
	"{:0\"\\0"
	"v{{{{\"\\0"
	"{:{:\"\\0"
	"{:{\"\\0"
	"v={v=\"\\0"
	"v=\"\\0"
	"{:{:{:{\"\\0"
```

The `\0` is common to all of them, that may be the *actual* minimum case, instead of what go-fuzz's minimizer is finding.
