### ISSUE TITLE
panic on {"\0 input

### ISSUE THREAD

**Issue by gregory-m** [hashicorp/hcl#194]
### HCL Template
```hcl
{"\0
```

### Expected behavior
Return error

### Actual behavior
Panic

### Steps to reproduce
```
package main

import (
	"fmt"

	"github.com/hashicorp/hcl"
)

func main() {
	ast, err := hcl.ParseString(`{"\0`)
	fmt.Println(ast, err)
}

```

Thanks to @dvyukov for github.com/dvyukov/go-fuzz

**Comment by sethvargo** [comment]
Here's the panic for context:

```
panic: bytes.Buffer: UnreadRune: previous operation was not ReadRune

goroutine 1 [running]:
github.com/hashicorp/hcl/json/scanner.(*Scanner).unread(0xc420070410)
	/Users/sethvargo/Development/go/src/github.com/hashicorp/hcl/json/scanner/scanner.go:103 +0xc7
github.com/hashicorp/hcl/json/scanner.(*Scanner).scanDigits(0xc420070410, 0x30, 0x8, 0x2, 0x5c200417f0)
	/Users/sethvargo/Development/go/src/github.com/hashicorp/hcl/json/scanner/scanner.go:359 +0x89
github.com/hashicorp/hcl/json/scanner.(*Scanner).scanEscape(0xc420070410, 0x5c)
	/Users/sethvargo/Development/go/src/github.com/hashicorp/hcl/json/scanner/scanner.go:331 +0xf2
github.com/hashicorp/hcl/json/scanner.(*Scanner).scanString(0xc420070410)
	/Users/sethvargo/Development/go/src/github.com/hashicorp/hcl/json/scanner/scanner.go:315 +0xa4
github.com/hashicorp/hcl/json/scanner.(*Scanner).Scan(0xc420070410, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/sethvargo/Development/go/src/github.com/hashicorp/hcl/json/scanner/scanner.go:166 +0x2fa
github.com/hashicorp/hcl/json/parser.(*Parser).scan(0xc420041df0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/sethvargo/Development/go/src/github.com/hashicorp/hcl/json/parser/parser.go:272 +0x71
github.com/hashicorp/hcl/json/parser.(*Parser).objectKey(0xc420041df0, 0x10ff320, 0xc420041df0, 0xc420041df0, 0x8, 0x18)
	/Users/sethvargo/Development/go/src/github.com/hashicorp/hcl/json/parser/parser.go:131 +0xa3
github.com/hashicorp/hcl/json/parser.(*Parser).objectItem(0xc420041df0, 0x0, 0x0, 0x0)
	/Users/sethvargo/Development/go/src/github.com/hashicorp/hcl/json/parser/parser.go:97 +0xb4
github.com/hashicorp/hcl/json/parser.(*Parser).objectList(0xc420041df0, 0x0, 0x0, 0x0)
	/Users/sethvargo/Development/go/src/github.com/hashicorp/hcl/json/parser/parser.go:71 +0xef
github.com/hashicorp/hcl/json/parser.(*Parser).objectType(0xc420041df0, 0x0, 0x0, 0x0)
	/Users/sethvargo/Development/go/src/github.com/hashicorp/hcl/json/parser/parser.go:200 +0xb1
github.com/hashicorp/hcl/json/parser.(*Parser).object(0xc420041df0, 0x0, 0x0, 0x0)
	/Users/sethvargo/Development/go/src/github.com/hashicorp/hcl/json/parser/parser.go:185 +0xf7
github.com/hashicorp/hcl/json/parser.(*Parser).Parse(0xc420041df0, 0xc420070410, 0x1, 0x1)
	/Users/sethvargo/Development/go/src/github.com/hashicorp/hcl/json/parser/parser.go:48 +0xd4
github.com/hashicorp/hcl/json/parser.Parse(0xc42000e2e8, 0x4, 0x8, 0x2, 0x4, 0x8)
	/Users/sethvargo/Development/go/src/github.com/hashicorp/hcl/json/parser/parser.go:34 +0x116
github.com/hashicorp/hcl.parse(0xc42000e2e8, 0x4, 0x8, 0xc42000e2e8, 0x4, 0x8)
	/Users/sethvargo/Development/go/src/github.com/hashicorp/hcl/parse.go:28 +0x76
github.com/hashicorp/hcl.ParseString(0x10f801d, 0x4, 0x0, 0x0, 0x0)
	/Users/sethvargo/Development/go/src/github.com/hashicorp/hcl/parse.go:20 +0x60
main.main()
	/Users/sethvargo/Development/go/src/github.com/sethvargo/playground/main.go:10 +0x3a
exit status 2
```
