### ISSUE TITLE
HCL encoder panic on writing nested lists

### ISSUE THREAD

**Issue by jleeh** [hashicorp/hcl#269]
### HCL Template
```hcl
env_vars = [
  [
    "key",
    "value"
  ],
  [
    "key2",
    "value2"
  ],
  [
    "key3",
    "value3"
  ]
]
```
When decoding this file using `hcl.decode`, I successfully can unmarshall it to a `map[string]interface{}` with the correct results. Although, when I then try to encode it to write back to file, I see a panic.

### Expected behavior
Successful encoding of HCL with nested lists and feature parity between the decoder & encoder.

### Actual behavior
Upon encoding, I get this panic:
```
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/hashicorp/hcl/hcl/printer.(*printer).objectItem(0xc0003816c0, 0xc00039e360, 0x0, 0x0, 0x0)
        /c/devgo/src/github.com/hashicorp/hcl/hcl/printer/nodes.go:245 +0x620
github.com/hashicorp/hcl/hcl/printer.(*printer).output(0xc0003816c0, 0xb74f00, 0xc00039e360, 0x0, 0x0, 0x0)
        /c/devgo/src/github.com/hashicorp/hcl/hcl/printer/nodes.go:205 +0xd01
github.com/hashicorp/hcl/hcl/printer.(*printer).output(0xc0003816c0, 0xbdbd40, 0xc00039c160, 0x0, 0x0, 0x0)
        /c/devgo/src/github.com/hashicorp/hcl/hcl/printer/nodes.go:174 +0x4d1
github.com/hashicorp/hcl/hcl/printer.(*printer).objectItem(0xc0003816c0, 0xc00039e5a0, 0x0, 0x0, 0x0)
        /c/devgo/src/github.com/hashicorp/hcl/hcl/printer/nodes.go:274 +0x2e7
github.com/hashicorp/hcl/hcl/printer.(*printer).output(0xc0003816c0, 0xb74f00, 0xc00039e5a0, 0x0, 0x0, 0x0)
        /c/devgo/src/github.com/hashicorp/hcl/hcl/printer/nodes.go:205 +0xd01
github.com/hashicorp/hcl/hcl/printer.(*printer).output(0xc0003816c0, 0xbdbd40, 0xc00039c1a0, 0x0, 0x0, 0x0)
        /c/devgo/src/github.com/hashicorp/hcl/hcl/printer/nodes.go:174 +0x4d1
github.com/hashicorp/hcl/hcl/printer.(*printer).output(0xc0003816c0, 0xb74e00, 0xc00039a0f0, 0x0, 0x0, 0x0)
        /c/devgo/src/github.com/hashicorp/hcl/hcl/printer/nodes.go:116 +0xef5
github.com/hashicorp/hcl/hcl/printer.(*Config).Fprint(0x12794e8, 0xd54140, 0xc000381650, 0xd57000, 0xc00039a0f0, 0x12da601, 0xc000381650)
        /c/devgo/src/github.com/hashicorp/hcl/hcl/printer/printer.go:32 +0x159
github.com/hashicorp/hcl/hcl/printer.Fprint(0xd54140, 0xc000381650, 0xd57000, 0xc00039a0f0, 0x0, 0x1)
        /c/devgo/src/github.com/hashicorp/hcl/hcl/printer/printer.go:48 +0x55
github.com/rodaine/hclencoder.Encode(0xb51780, 0xc00039a060, 0x7fffe04898cb, 0x7, 0x7fffe04898d6, 0x7, 0xc4ce64)
        /c/devgo/src/github.com/rodaine/hclencoder/hclencoder.go:31 +0x204
github.com/smartcontractkit/chaintf/hcl.getBytesFromExtension(0x7fffe04898be, 0x9, 0x7fffe04898cb, 0x7, 0x7fffe04898d6, 0x7, 0xc00039a060, 0x1, 0x9c0000000000004a, 0x0, ...)
        /c/devgo/src/github.com/smartcontractkit/chaintf/hcl/writer.go:64 +0xba
github.com/smartcontractkit/chaintf/hcl.WriteConfig(0x7fffe04898be, 0x9, 0x7fffe04898cb, 0x7, 0x7fffe04898d6, 0x7, 0xc00039a060, 0x0, 0x0)
        /c/devgo/src/github.com/smartcontractkit/chaintf/hcl/writer.go:13 +0x83
github.com/smartcontractkit/chaintf/cmd.update(0x12b2540, 0xc0003693b0, 0x1, 0x9)
        /c/devgo/src/github.com/smartcontractkit/chaintf/cmd/update.go:28 +0x2cb
github.com/spf13/cobra.(*Command).execute(0x12b2540, 0xc000369320, 0x9, 0x9, 0x12b2540, 0xc000369320)
        /c/devgo/src/github.com/spf13/cobra/command.go:766 +0x2cc
github.com/spf13/cobra.(*Command).ExecuteC(0x12b2080, 0xc0001f5f88, 0x4073b0, 0xc00008e058)
        /c/devgo/src/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/spf13/cobra.(*Command).Execute(0x12b2080, 0x0, 0x0)
        /c/devgo/src/github.com/spf13/cobra/command.go:800 +0x2b
github.com/smartcontractkit/chaintf/cmd.Execute()
        /c/devgo/src/github.com/smartcontractkit/chaintf/cmd/root.go:23 +0x2d
main.main()
        /c/devgo/src/github.com/smartcontractkit/chaintf/main.go:6 +0x20
```

### Steps to reproduce
1. Decode HCL template in issue
2. Change a value in the HCL
3. Encode the result to write back to file

### References
This is similar to #234. Even though Terraform accepts the HCL in the template above, if I try to work around this issue by using JSON, I get the same error (`expected: STRING got: LBRACK`) found in the linked issue.

Terraform can parse HCL with nested lists, but it cant parse JSON with nested lists.

**Comment by jleeh** [comment]
Closing this as after debugging I've found it's an issue with https://github.com/rodaine/hclencoder rather than the printer. Working on a fix for the hclencoder repo.
