### ISSUE TITLE
"Index out of range" panic when decoding malformed input

### ISSUE THREAD

**Issue by AGWA** [hashicorp/hcl#73]
The following HCL causes an "index out of range" panic when you try to decode it:

```
section {
        subsection {
        }
}
section "subsection" {
}
```

Test program:
```go
package main

import (
        "github.com/hashicorp/hcl"
)

var hclText = `
section {
        subsection {
        }
}
section "subsection" {
}
`

func main () {
        var shadow interface{}
        hcl.Decode(&shadow, hclText)
}
```

Backtrace:
```
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/hashicorp/hcl.(*decoder).decodeMap(0xc820087e60, 0xc82000ab40, 0xf, 0x7f36c08a11c0, 0xc82000e8e0, 0x4ebfe0, 0xc820036078, 0xd5, 0x0, 0x0)
	gopath/src/github.com/hashicorp/hcl/decoder.go:301 +0x1081
github.com/hashicorp/hcl.(*decoder).decode(0xc820087e60, 0xc82000ab40, 0xf, 0x7f36c08a12f0, 0xc820020360, 0x4ebfe0, 0xc820036078, 0xd5, 0x0, 0x0)
	gopath/src/github.com/hashicorp/hcl/decoder.go:83 +0x69c
github.com/hashicorp/hcl.(*decoder).decodeSlice(0xc820087e60, 0xc82000aae0, 0xc, 0x7f36c08a11c0, 0xc82000e8a0, 0x4e44c0, 0xc82000e840, 0x57, 0x0, 0x0)
	gopath/src/github.com/hashicorp/hcl/decoder.go:395 +0x5c6
github.com/hashicorp/hcl.(*decoder).decode(0xc820087e60, 0xc82000aae0, 0xc, 0x7f36c08a11c0, 0xc82000e8a0, 0x4eba20, 0xc82000ab00, 0xd4, 0x0, 0x0)
	gopath/src/github.com/hashicorp/hcl/decoder.go:87 +0x774
github.com/hashicorp/hcl.(*decoder).decodeMap(0xc820087e60, 0x5405e0, 0x4, 0x7f36c08a11c0, 0xc82000e5c0, 0x4ebfe0, 0xc820010510, 0x15, 0x0, 0x0)
	gopath/src/github.com/hashicorp/hcl/decoder.go:330 +0xf1d
github.com/hashicorp/hcl.(*decoder).decode(0xc820087e60, 0x5405e0, 0x4, 0x7f36c08a11c0, 0xc82000e5c0, 0x4eba20, 0xc82000a4b0, 0xd4, 0x0, 0x0)
	gopath/src/github.com/hashicorp/hcl/decoder.go:83 +0x69c
github.com/hashicorp/hcl.(*decoder).decodeInterface(0xc820087e60, 0x5405e0, 0x4, 0x7f36c08a11c0, 0xc82000e5c0, 0x4eba20, 0xc82000a4b0, 0xd4, 0x0, 0x0)
	gopath/src/github.com/hashicorp/hcl/decoder.go:249 +0x384
github.com/hashicorp/hcl.(*decoder).decode(0xc820087e60, 0x5405e0, 0x4, 0x7f36c08a11c0, 0xc82000e5c0, 0x4eba20, 0xc82000a4b0, 0xd4, 0x0, 0x0)
	gopath/src/github.com/hashicorp/hcl/decoder.go:81 +0x628
github.com/hashicorp/hcl.DecodeObject(0x4df000, 0xc82000a4b0, 0x7f36c08a11c0, 0xc82000e5c0, 0x0, 0x0)
	gopath/src/github.com/hashicorp/hcl/decoder.go:43 +0x25f
github.com/hashicorp/hcl.Decode(0x4df000, 0xc82000a4b0, 0x56ae60, 0x37, 0x0, 0x0)
	gopath/src/github.com/hashicorp/hcl/decoder.go:26 +0xb9
main.main()
	crash_hcl.go:18 +0x5f

```

**Comment by sethvargo** [comment]
Not sure if this is valid HCL, but it definitely shouldn't panic. Reproduced and tagged.

**Comment by mitchellh** [comment]
This is fixed!
